model:
  model_path: "/media/vishal/workspace/projects/VLA/modality_alignment/f2q_vla_artifacts"
  type: "f2q_vla"
  freeze_vision_tower: true
  freeze_llm: true
  freeze_projector: false

data:
  dataset_path: "/media/vishal/datasets/pixmo/metadata_cleaned/"
  test_split_ratio: 0.01
  image_size_height: 360
  image_size_width: 640
  dataloader_num_workers: 6

training:
  output_dir: "/media/vishal/workspace/projects/VLA/checkpoints/stage1_projector"
  num_train_epochs: 1
  learning_rate: 2.0e-4
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 16
  report_to: "tensorboard"
  save_steps: 500
  logging_steps: 100

lora:
  enabled: false
